name: chat_firestore
description: "Flutter chat app using Firebase as BE with Authentication and Firestore"
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"

flutter_intl:
  enabled: true
  main_locale: pl_PL

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  rename: ^3.0.2
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  firebase_storage: ^12.3.2
  firebase_crashlytics: ^4.1.3
  cloud_firestore: ^5.4.4
  get_it: ^8.0.0
  fimber: ^0.7.0
  auto_route: ^9.2.2
  intl: ^0.19.0
  intl_utils: ^2.8.7
  dartz: ^0.10.1
  uuid: ^4.5.1
  freezed_annotation: ^2.4.4
  dio: ^5.7.0
  flutter_bloc: ^8.1.6
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.13
  freezed: ^2.5.7

flutter:
  uses-material-design: true
